version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      POSTGRES_USER=${POSTGRES_USER}
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      POSTGRES_DB=${POSTGRES_DB}
      POSTGRES_PORT=${POSTGRES_PORT}
      POSTGRES_SERVER=${POSTGRES_SERVER}
      REDIS_URL=${REDIS_URL}
      SECRET_KEY=${SECRET_KEY}
      ALGORITHM=${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    volumes:
      ./uploads:/app/uploads
    command: >
      sh -c "alembic upgrade head && 
             uvicorn main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER=${POSTGRES_USER}
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      POSTGRES_DB=${POSTGRES_DB}
    ports:
      "${POSTGRES_PORT}:5432"
    volumes:
      postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      "6379:6379"

volumes:
  postgres_data: