"""Project v 3 worked

Revision ID: 16c1e7c6dffe
Revises: d045ee9a2a6b
Create Date: 2025-04-05 21:02:02.198265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c1e7c6dffe'
down_revision: Union[str, None] = 'd045ee9a2a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('changes', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_at')
    op.drop_column('task_history', 'changes')
    # ### end Alembic commands ###
