"""Project v 2.8 worked

Revision ID: d045ee9a2a6b
Revises: efc9615f46b0
Create Date: 2025-04-05 20:30:52.656903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd045ee9a2a6b'
down_revision: Union[str, None] = 'efc9615f46b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_history', sa.Column('old_title', sa.String(length=255), nullable=True))
    op.add_column('article_history', sa.Column('new_title', sa.String(length=255), nullable=True))
    op.add_column('article_history', sa.Column('old_content', sa.String(length=5000), nullable=True))
    op.add_column('article_history', sa.Column('new_content', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_history', 'new_content')
    op.drop_column('article_history', 'old_content')
    op.drop_column('article_history', 'new_title')
    op.drop_column('article_history', 'old_title')
    # ### end Alembic commands ###
